#!/bin/sh

cd ~
rm mac Brewfile
curl --remote-name https://raw.githubusercontent.com/roberttaraya/laptop/for-work-mods/mac
curl --remote-name https://raw.githubusercontent.com/roberttaraya/laptop/for-work-mods/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
