#!/bin/bash

# Taken from the monfresh laptop script (with pieces of other scripts)!
# Be prepared to turn your laptop (or desktop)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  printf "\n$fmt\n" "$@"
}

append_to_file() {
  local file="$1"
  local text="$2"

  if ! grep -qs "^$text$" "$file"; then
    printf "\n%s\n" "$text" >> "$file"
  fi
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

if ! command -v xcode-select -p >/dev/null; then
#if [ ! -d "$HOME/Library/Developer/CommandLineTools/" ]; then
  fancy_echo "No Command Line Tools found. Installing Xcode..."
  xcode-select --install
else
  fancy_echo "Xcode installed. Skipping..."
fi

if [ ! -d "$HOME/.oh-my-zsh/" ]; then
  ##
  # Install Oh My Zsh
  fancy_echo 'Installing Oh My Zsh...'
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
else
  fancy_echo 'Oh My Zsh is already installed'
fi

shell_file="$HOME/.zshrc"

if [ ! -f "$HOME/.oh-my-zsh/themes/roberttaraya.zsh-theme" ]; then
  fancy_echo 'Copying roberttaraya.zsh-theme from gist...'
  cd "$HOME/.oh-my-zsh/themes/"
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/0573d75c4ae298e64998/raw/234157c735cfe12c4eefba962d89bb6402642bbb/roberttaraya.zsh-theme
else
  fancy_echo 'roberttaraya.zsh-theme already exists. Skipping...'
fi

fancy_echo "Setting Zshrc..."
cd
curl --remote-name https://gist.githubusercontent.com/roberttaraya/ca2ad3a47f0bed3b0d29/raw/33e80a8e452959ac40f16228c680beab79d36956/.zshrc

brew_is_installed() {
  brew list -1 | grep -Fsx "$1"
}

tap_is_installed() {
  brew tap -1 | grep -Fsx "$1"
}

gem_install_or_update() {
  if gem list "$1" | grep "^$1 ("; then
    fancy_echo "Updating %s ..." "$1"
    gem update "$@"
  else
    fancy_echo "Installing %s ..." "$1"
    gem install "$@"
  fi
}

app_is_installed() {
  local app_name
  app_name=$(echo "$1" | cut -d'-' -f1)
  find /Applications -iname "$app_name*" -maxdepth 1 | egrep '.*' > /dev/null
}

latest_installed_ruby() {
  find "$HOME/.rubies" -maxdepth 1 -name 'ruby-*' | tail -n1 | egrep -o '\d+\.\d+\.\d+'
}

switch_to_latest_ruby() {
  source /usr/local/share/chruby/chruby.sh
  chruby "ruby-$(latest_installed_ruby)"
}

append_to_file "$shell_file" "alias laptop='bash <(curl -s https://raw.githubusercontent.com/roberttaraya/laptop/master/laptop)'"
append_to_file "$shell_file" 'export PATH="$HOME/.bin:$PATH"'

##
# Install & update Homebrew
if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  append_to_file "$shell_file" 'export PATH="/usr/local/bin:$PATH"'
else
  fancy_echo 'Homebrew already installed. Skipping ...'
fi

# Remove brew-cask since it is now installed as part of brew tap caskroom/cask.
# See https://github.com/caskroom/homebrew-cask/releases/tag/v0.60.0
if brew_is_installed 'brew-cask'; then
  brew uninstall --force 'brew-cask'
fi

if tap_is_installed 'caskroom/versions'; then
  brew untap caskroom/versions
fi

fancy_echo 'Updating Homebrew ...'
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
cd

fancy_echo 'Verifying the Homebrew installation...'
if brew doctor; then
  fancy_echo 'Your Homebrew installation is good to go.'
else
  fancy_echo 'Your Homebrew installation reported some errors or warnings.'
  fancy_echo 'Review the Homebrew messages to see if any action is needed.'
fi

fancy_echo 'Installing formulas and casks from the Brewfile ...'
if brew bundle --file="$HOME/Brewfile"; then
  fancy_echo 'All formulas and casks were installed successfully.'
else
  fancy_echo 'Some formulas or casks failed to install.'
  fancy_echo 'This is usually due to one of the Mac apps being already'
  fancy_echo 'installed, in which case, you can ignore these errors.'
fi


##
# Install Node, nvm
fancy_echo 'Checking on Node.js installation...'

if ! brew_is_installed 'nvm'; then
  fancy_echo 'Installing nvm...'
  brew install nvm
else
  fancy_echo 'nvm already installed. Skipping...'
fi

if ! command -v nvm > /dev/null; then
  source /usr/local/opt/nvm/nvm.sh
  append_to_file "$shell_file" 'source /usr/local/opt/nvm/nvm.sh'
fi

if ! command -v node > /dev/null; then
  fancy_echo 'Installing Node.js...'
  nvm install node
else
  fancy_echo 'Node.js already installed. Skipping...'
fi

fancy_echo '...Finished Node.js installation checks.'

append_to_file "$HOME/.gemrc" 'gem: --no-document'


##
# Install Ruby, chruby
if ! brew_is_installed 'chruby'; then
  fancy_echo 'Installing chruby...'
  brew install chruby
else
  fancy_echo 'chruby already installed. Skipping...'
fi

if ! brew_is_installed 'ruby-install'; then
  fancy_echo 'Installing ruby-install...'
  brew install ruby-install
  ruby-install ruby
else
  fancy_echo 'ruby-install already installed. Skipping...'

  if [ ! -d "$HOME/.rubies/" ]; then
    fancy_echo "Installing latest stable Ruby version..."
    ruby-install ruby
  fi
fi

latest_stable_ruby="$(cat < "$HOME/.cache/ruby-install/ruby/stable.txt" | tail -n1)"
if ! [ "$latest_stable_ruby" = "$(latest_installed_ruby)" ]; then
  fancy_echo "Installing latest stable Ruby version: $latest_stable_ruby"
  ruby-install ruby
else
  fancy_echo 'You have the latest version of Ruby'
fi

if ! command -v chruby > /dev/null; then
  append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
  append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
  append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
fi
switch_to_latest_ruby


##
# Install & update Rubygems
fancy_echo 'Updating Rubygems...'
gem update --system

fancy_echo 'Installing or updating Bundler...'
gem_install_or_update 'bundler'

fancy_echo 'Configuring Bundler...'
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))

fancy_echo 'Installing Rails...'
gem install rails

fancy_echo 'Installing Jekyll...'
gem install jekyll

fancy_echo '...Finished Ruby installation checks.'


##
# Install & run Docker for Mac
if app_is_installed 'Docker'; then
  fancy_echo 'Docker already installed. Skipping...'
else
  fancy_echo 'Installing Docker...'
  docker_url=https://desktop.docker.com/mac/stable/amd64/Docker.dmg
  docker_dmg=/tmp/Docker.dmg
  docker_volume=/Volumes/Docker
  curl -s -o $docker_dmg $docker_url
  hdiutil attach $docker_dmg -nobrowse > /dev/null
  cp -a $docker_volume/Docker.app /Applications/
  hdiutil detach $docker_volume > /dev/null
  rm -f $docker_dmg
  fancy_echo '...Finished installing Docker'

  fancy_echo 'Ensuring Docker is running...'

  if ! /usr/local/bin/docker ps > "$tmp_output" 2>&1; then
    open /Applications/Docker.app
    fancy_echo "...Docker is running. You're good to go!"
  else
    fancy_echo 'TODO: Something is wrong with Docker. Needs troubleshooting...'
  fi
fi


##
# Configurations, Settings, & Preferences
if [ ! -d "$HOME/Library/Application Support/iTerm2/" ]; then
  mkdir -p "$HOME/Library/Application Support/iTerm2/"
fi

if [ ! -f "$HOME/Library/Application Support/iTerm2/com.googlecode.iterm2.plist" ]; then
  fancy_echo 'Copying iterm2 Preferences...'
  cd "$HOME/Library/Application Support/iTerm2/"
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/d927550c4502bc31d7e1a4d558cbce95/raw/2c740685a80d25d100e2166dfd0ebbd5f9d80e6b/com.googlecode.iterm2.plist
  fancy_echo "TODO: Go to iterm2 settings to load preferences manually: ~/Library/Application Support/iTerm2/"
else
  fancy_echo 'iterm2 Preferences already copied from gist. Skipping...'
fi


fancy_echo 'Setting up Sublime Text...'
if [ ! -d "$HOME/Library/Application Support/Sublime Text/Packages/User/" ]; then
  mkdir -p "$HOME/Library/Application Support/Sublime Text/Packages/User/"
fi

if [ ! -f "$HOME/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings" ]; then
  fancy_echo 'Copying Sublime Text Preferences...'
  cd "$HOME/Library/Application Support/Sublime Text/Packages/User/"
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/39778896c203977b8984/raw/9d3dd75238add1d9a770b91b804885eae45f710a/Preferences.sublime-settings
else
  fancy_echo 'Sublime Text preferences already set. Skipping...'
fi

if ! command -v subl >/dev/null; then
  fancy_echo '...creating a symbolic link for subl...'
  ln -s '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' /usr/local/bin/subl
fi


fancy_echo 'Setting up VS Code...'
if [ ! -d "$HOME/Library/Application Support/Code/User/" ]; then
  mkdir -p "$HOME/Library/Application Support/Code/User/"
  #open /Applications/Visual\ Studio\ Code.app
fi

if [ ! -f "$HOME/Library/Application Support/Code/User/keybindings.json" ]; then
  fancy_echo 'Copying VS Code Keybinding Preferences...'
  cd "$HOME/Library/Application Support/Code/User/"
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/2fbfbe56ecb842b45586fba093693c37/raw/1a5da2feff3eea1a44cc291deec977eb09a7e4c6/keybindings.json
else
  fancy_echo 'VS Code Keybinding Preferences already set. Skipping...'
fi

if [ ! -f "$HOME/Library/Application Support/Code/User/settings.json" ]; then
  fancy_echo 'Copying VS Code Editor Settings...'
  cd "$HOME/Library/Application Support/Code/User/"
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/f9afb3b59a5dbb4df4fc9d35865dbe05/raw/0270fa667431c9f09d84cb549f5ed334f1e0fbb3/settings.json
else
  fancy_echo 'VS Code editor settings already set. Skipping...'
fi

if ! command -v code >/dev/null; then
  fancy_echo '...creating a symbolic link for VS Code...'
  ln -s '/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' /usr/local/bin/code
fi

if [ ! -f "$HOME/laptop_setup_todo_list.md" ]; then
  cd
  curl --remote-name https://raw.githubusercontent.com/roberttaraya/laptop/master/laptop_setup_todo_list.md
  open /Applications/MacDown.app $HOME/laptop_setup_todo_list.md
fi

if [ ! -f "$HOME/.gitconfig" ]; then
  fancy_echo "...copying .gitconfig"
  cd
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/e1f85f06e1359ea0b7d7/raw/9aba1578a47f2d9a14133dd8ef906e5c31f45f68/.gitconfig
fi

if [ ! -f "$HOME/.gitignore_global" ]; then
  fancy_echo "...copying .gitignore_global"
  cd
  curl --remote-name https://gist.githubusercontent.com/roberttaraya/ae1580de25ff4859c0b5d3a2cbeca0a3/raw/d71de712ddcc1b50cae906b90b590c0ffa39a9fa/.gitignore_global
fi

fancy_echo '...creating a working directory for your code...'
if [ ! -d "$HOME/Workspace/" ]; then
  mkdir -p "$HOME/Workspace"
fi

fancy_echo '...downloading your avatar...'
if [! -f "$HOME/Documents/avatar.jpg" ]; then
  cd "$HOME/Documents"
  curl -L -o "Robert's avatar.jpg" https://drive.google.com/uc\?export\=download\&id\=0B3L6WzP1P-KjV1c3ZF82Mm1MOFU
fi

fancy_echo 'All done!'
exec zsh
